CompanyBlog/blog_posts/views.py
# blogposts/views.py
from flask import render_template, url_for, request, redirect, Blueprint, flash, abort
from flask_login import current_user, login_required

from CompanyBlog.models import db
from CompanyBlog.models import BlogPost
from CompanyBlog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts', __name__)


# create a blog post
@blog_posts.route('/create', methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(title=form.title.data, text=form.text.data, user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        print('blog created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html', form=form)

#view blogpost


@blog_posts.route('/<int:blog_post_id>')
def blog(blog_post_id):
    blog_find = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog.html', title=blog_find.title,
                                        date=blog_find.date,
                                        post=blog_find)


# update blogpost
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET','POST'])
@login_required
def blog_update(blog_post_id):
    b_update = BlogPost.query.get_or_404(blog_post_id)

    if b_update.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        b_update.title = form.title.data
        b_update.text = form.text.data
        db.session.commit()
        print('blog updated')
        return redirect(url_for('blog_posts.blog', blog_post_id=blog_post_id))

    elif request.method == 'GET':
        form.title.data = b_update.title
        form.text.data = b_update.text

    return render_template('create_post.html', form=form, title='Updating')


# Delete a blog post
@blog_posts.route('/<int:blog_post_id>/delete', methods=['GET', 'POST'])
@login_required
def deleteb(blog_post_id):
    d_post = BlogPost.query.get_or_404(blog_post_id)
    if d_post.author != current_user:
        abort(403)
    db.session.delete(d_post)
    db.session.commit()
    print('post deleted')
    return redirect(url_for('core.index'))

CompanyBlog/core/views.py
# core/views

from flask import render_template, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from CompanyBlog.models import BlogPost
import stripe

# Blueprint for for better organisation
core = Blueprint('core', __name__)

# payment keys - from stripe

public_key = "pk_test_51HtqirEqqKeUnAHaud7Mr19azD5DSTUuiVG8LfKhVoy665ZSpUL2vdKzJotdu4DmcoSVWKRSOhAXfEhFf09HURqQ001GqMBNRB"
stripe.api_key = "sk_test_51HtqirEqqKeUnAHau5w6T3orSkAptt8zLwFZWzhhvXbNFqX4k54HSt3GdW1KAwC0zj8f20zd6XmxNJT3ZpKC5Wc0008eKADEEB"


@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    blog_post = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template('index.html', blog_post=blog_post)

@core.route('/info')
def info():
    return render_template('info.html')


@core.route('/donation')
@login_required
def donation():
    return render_template('donation.html', public_key=public_key)




@core.route('/payment', methods=["POST"])
@login_required
def payment():
    #customer info
    customer = stripe.Customer.create(email=request.form['stripeEmail'],
                                      source=request.form['stripeToken'])

    # payment information
    charge = stripe.Charge.create(
        customer=customer.id,
        amount=1000,
        currency='INR',
        description='Test donation'
    )

    return render_template('Pthankyou.html')

CompanyBlog/users/views.py
# views to be created
from flask import render_template, url_for, request, Blueprint, redirect, flash
from flask_login import login_user, logout_user, current_user, login_required
from CompanyBlog import db
from CompanyBlog.models import User, BlogPost
from CompanyBlog.users.forms import Register, LoginForm, Update
from CompanyBlog.users.picture_handler import add_profilepic
from sqlalchemy.exc import IntegrityError

users = Blueprint('users', __name__)


# register

@users.route('/register',methods=['GET', 'POST'])
def register():
    message = ""
    form = Register()

    if form.validate_on_submit():
        user = User(email=form.Email.data,
                    username=form.Username.data,
                    password=form.password.data)
        try:
            db.session.add(user)
            db.session.commit()
            flash('Thanks for registering')
            return redirect(url_for('users.login'))
        except IntegrityError:
            message = "username or email id already exists !!"

    return render_template('register.html', form=form, message=message)


# login
@users.route('/login', methods=['GET','POST'])
def login():
    message = ""
    form = LoginForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            if User.check_password(user, password=form.password.data) and user is not None:
                login_user(user)
                message = "Login Success"
                return redirect(url_for('core.index'))
            else:
                message = "wrong password"
        except AttributeError:
            message = "Values entered is not correct"

    return render_template('login.html', form=form, error=message)

# logout
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))


# user account view ( update info )
@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = Update()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            picture = add_profilepic(form.picture.data, username)
            current_user.profile_image = picture

            current_user.username = form.Username.data
            current_user.email = form.Email.data
            db.session.commit()
            flash('user account updated')
            return redirect(url_for('users.account'))

    elif request.method == "GET":
            form.Username.data = current_user.username
            form.Email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


# Login blogpost view
@users.route('/<username>')
def userposts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc().paginate(page=page, per_page=3))
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

CompanyBlog/templates/Pthankyou.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
    <h1>Thank you for your generous donation {{current_user.username}}</h1>
    <p>A payment confirmation will be sent to your mail(joking)</p>
</div>

{% endblock %}

CompanyBlog/templates/account.html
{% extends 'base.html'%}
{%  block content %}
    <div class="jumbotron">
        <div align="center">
            <h1>Welcome {{current_user.username}}</h1>
            <img align="center" src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
        </div>
    </div>

<div class="container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{form.hidden_tag()}}

        {{form.Username.label}} {{form.Username}}<br><br>

        {{form.Email.label}} {{form.Email}}<br><br>

        {{form.picture.label}} {{form.picture}}<br><br>

        {{form.Submit()}}


    </form>
</div>
{% endblock %}

CompanyBlog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<!-- jQuery and JS bundle w/ Popper.js -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">FirstBLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('core.index')}}">Home<span class="sr-only">(current)</span></a>
      </li>

        <li class="nav-item active">
        <a class="nav-link" href="{{url_for('core.info')}}">ABOUT<span class="sr-only">(current)</span></a>
      </li>

      {% if current_user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('users.account')}}">ACCOUNT<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('users.logout')}}">LOG OUT<span class="sr-only">(current)</span></a>
      </li>

        <li class="nav-item active">
        <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">CREATE POST<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('core.donation')}}">Donate<span class="sr-only">(current)</span></a>
      </li>

      {% else %}

      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('users.register')}}">REGISTER<span class="sr-only">(current)</span></a>
      </li>

        <li class="nav-item active">
        <a class="nav-link" href="{{url_for('users.login')}}">LOGIN<span class="sr-only">(current)</span></a>
      </li>

      {% endif %}


    </ul>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

CompanyBlog/templates/blog.html
{% extends 'base.html'%}
{% block content %}
<div class="jumbotron">
    <h1>{{post.title}}</h1>
    <h2>Written by:{{post.author.username}}</h2>
    <h3>Published at: {{post.date.strftime('%B %d, %Y')}}</h3>
    <p>{{post.text}}</p>
</div>

 {% if post.author == current_user %}
    <a href="{{url_for('blog_posts.blog_update',blog_post_id=post.id)}}"> update </a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal" >Delete</button>

{% endif %}

</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the post </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <form action="{{url_for('blog_posts.deleteb',blog_post_id=post.id)}}">
              <input class="btn btn-danger" type="submit" value="Delete">
          </form>
      </div>
    </div>
  </div>
  </div>
</div>

{% endblock %}

CompanyBlog/templates/create_post.html
{% extends 'base.html'%}
{% block content %}

<div class="container">
    <form class="form-group" method="POST">
        {{form.hidden_tag()}}

        <div class="form-group">
            {{form.title.label(class="form-control-label")}}
            {{form.title(class="form-control form-control-lg")}}
        </div>

        <div class="form-group">
            {{form.text.label(class="form-control-label")}}
            {{form.text(class="form-control form-control-lg")}}
        </div>
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>

    </form>
</div>
{% endblock %}

CompanyBlog/templates/donation.html
{% extends 'base.html'%}
{% block content %}

<div class="jumbotron">
    <h1>Welcome to our donation page </h1>
    <h2>Would you like to make a donation ? (Just to test the functionality ) </h2>
    <form action="{{url_for('core.payment')}}" method="POST">
        <script
        src = "https://checkout.stripe.com/checkout.js"
        class="stripe-button"
        data-key="{{public_key}}"
        data-amount="1000"
        data-name="Donation test"
        data-description="Donation site"
        data-locale="auto"
        data-zip-code="true"></script>
    </form>
</div>
{% endblock %}

CompanyBlog/templates/index.html
{% extends "base.html"%}
{% block content %}
    <div class="jumbotron">
        <h1>COMPANY BLOG PAGE </h1>
        <div class="container">
            {% for post in blog_post.items %}
            <div class="card">
                <h2><a class="card-title" href="{{url_for('blog_posts.blog',blog_post_id=post.id)}}">{{post.title}}</a></h2>
                <a href="{{url_for('users.userposts',username=post.author.username)}}">Written By :{{post.author.username}}</a>
                <p>published on:{{post.date.strftime('%Y-%m-%d')}}</p>
                <a class="btn btn-primary" href="{{url_for('blog_posts.blog',blog_post_id=post.id)}}">Read blog post</a>
            </div>

            {% endfor %}
        </div>

    </div>

    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
          {% for page_num in blog_post.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
            {% if blog_post.page==page_num %}
            <li class="page-item disabled"><a class="page-link" href="{{url_for('core.index',page=page_num)}}"></a>{{page_num}}</li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="{{url_for('core.index',page=page_num)}}"></a>{{page_num}}</li>
            {% endif %}
          {% endfor %}
      </ul>
    </nav>
{% endblock %}

CompanyBlog/templates/info.html
{% extends "base.html"%}
{% block content %}
<div class="jumbotron">
    <h1>COMAPANY INFORMATION</h1>
    <p>Info about the company will be displayed here </p>
</div>
{% endblock %}

CompanyBlog/templates/login.html
{% extends 'base.html'%}
{% block content %}
{% if error %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{error}}!!</strong>Please try again
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
<div class="card bg-light mb-2" align="centre" style="width: 24em;margin:0 auto;">
  <div class="card-header" align="center">Log in!!</div>
    <div class="card text-left">
<form method="POST">
    {{form.hidden_tag()}}
    <br>
    {{form.email.label(class="form-group ")}} {{form.email(class=" .col -7")}}
    <br>
    {{form.password.label(class="form-group ")}}{{form.password(class=" .col -7")}}
    <br>
    <div align="center">
    {{form.submit(class="btn btn-success")}}
        </div>
</form>
    </div>
</div>


{% endblock %}

CompanyBlog/templates/register.html
{% extends 'base.html'%}
{% block content %}
{% if message %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{message}}!!</strong>Please try again
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}
<br>

<div class="container">
<div class="col d-flex justify-content-center" >
<div class="card bg-light mb-2" align="centre" style="max-width: 80rem;">
  <div class="card-header" align="center">Register Now!!</div>
    <div class="card text-left">
    <form method="POST">
        {{form.hidden_tag()}}
        <br>{{form.Email.label(class="form-group ")}} {{form.Email(class=" .col -7")}}
        {{form.Username.label(class="form-group")}} {{form.Username(class=" .col -7")}}
        <br>
        {{form.password.label(class="form-group")}} {{form.password(class=" .col -7")}}
        <br>
        {{form.pass_confirm.label(class="form-group")}} {{form.pass_confirm(class=" .col -7")}}
        <br>
        <div align="center">
        {{form.Submit(class="btn btn-success")}}
            <div>

            </div>
    </form>
</div>
</div>
</div>

</div>

{% endblock %}

CompanyBlog/templates/user_blog_posts.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <div align="center">
            <h1>Welcome to page for {{user.username}}</h1>1
            <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
        </div>
    </div>


{% for post in blog_posts.items %}
<h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
written by:<a href= "{{url_for('users.userposts',username=post.author.username)}}">{{post.author.username}}</a>
<p class="text-muted">Published on : {{post.date.strftime("%y-%m-%d")}}</p>
<br>
<p>{{post.text}}</p>
<br>

{% endfor %}
</div>


<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if blog_posts.page==page_num %}
        <li class="page-item disabled"><a class="page-link" href="{{url_for('users.userposts',username=user.username,page=page_num)}}"></a>{{page_num}}</li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="{{url_for('users.userposts',username=user.username,page=page_num)}}"></a>{{page_num}}</li>
        {% endif %}
      {% endfor %}
  </ul>
</nav>
{% endblock %}